version: '3'
services:
  app:
    build: .
    container_name: selenium_app
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
    environment:
      - CONFIG_FILE=/usr/src/app/config.json

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
